# quarkus:
#   datasource:
#     db-kind: mysql
#     username: root
#     password: xxxxxx
#     jdbc:
#       url: jdbc:mysql://localhost/testdb
#       max-size: 8
#       min-size: 2
#   hibernate-orm:
#     database:
#       generation: drop-and-create
#     log:
#       sql: false
#     sql-load-script: import.sql
quarkus:
  datasource:
    db-kind: h2
    username: root
    jdbc:
      url: jdbc:h2:mem:test
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: false
    sql-load-script: import.sql